apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: service-rss
  name: service-rss
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: service-rss
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: service-rss
    spec:
      containers:
      - args:
        - sh
        - -c
        - sh /wait-for.sh database-postgres:5432 -- php /configure-db.php && exec
          s6-svscan /etc/s6/
        env:
        - name: DB_HOST
          value: database-postgres
        - name: DB_NAME
          value: ttrss
        - name: DB_PASS
          value: ttrss
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: postgres
        - name: ENABLE_PLUGINS
          value: auth_internal,fever
        - name: SELF_URL_PATH
          value: http://localhost:181/
        - name: SINGLE_USER_MODE
          value: "true"
        image: wangqiru/ttrss:nightly
        imagePullPolicy: Always
        name: ttrss
        ports:
        - containerPort: 80
          protocol: TCP
        stdin: true
        tty: true
      restartPolicy: Always