apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: service-mercury
  name: service-mercury
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    io.kompose.service: service-mercury
  sessionAffinity: None
  type: ClusterIP