apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: database-postgres
  name: database-postgres
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    io.kompose.service: database-postgres
  sessionAffinity: None
  type: ClusterIP