apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: service-rss
  name: service-rss
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: "181"
    port: 181
    protocol: TCP
    targetPort: 80
  selector:
    io.kompose.service: service-rss
  sessionAffinity: None
  type: LoadBalancer