apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kompose.cmd: kompose up
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  generation: 1
  labels:
    io.kompose.service: service-browserless
  name: service-browserless
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/service-browserless
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      io.kompose.service: service-browserless
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: service-browserless
    spec:
      containers:
      - image: browserless/chrome
        imagePullPolicy: Always
        name: service-browserless
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
