apiVersion: v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: database-postgres
  name: database-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: database-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: database-postgres
    spec:
      containers:
      - env:
        - name: DB_EXTENSION
          value: pg_trgm
        - name: PG_PASSWORD
          value: ttrss
        image: sameersbn/postgresql:latest
        name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/
          name: postgres-data
      restartPolicy: Always
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-data
