apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: database-postgres
  name: database-postgres
  selfLink: /api/v1/namespaces/default/services/database-postgres
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    io.kompose.service: database-postgres
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
